version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
conda:
  environment: docs/environment.yml


sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements.txt

formats:
  - htmlzip
  - pdf
