version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - python docs/rmd_to_md_rtd.py   # 渲染 Rmd -> Markdown

conda:
  environment: docs/environment.yml   # conda 环境

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/source/conf.py

formats:
  - htmlzip
  - pdf
