version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # 安装 R 包 rmarkdown
    - Rscript -e 'install.packages("rmarkdown", repos="https://cloud.r-project.org")'

apt_packages:
  - r-base
  - libcurl4-openssl-dev
  - libssl-dev
  - libxml2-dev

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements.txt

formats:
  - htmlzip
  - pdf
