version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # 在 Sphinx 构建前，先把 CHESS.Rmd 转为 Markdown
    - python docs/rmd_to_md_rtd.py


sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements.txt
conda:
  environment: docs/environment.yml

formats:
  - htmlzip
  - pdf
