version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py   # 指向你的 conf.py 位置

python:
  install:
    - requirements: requirements.txt    # ✅ 仅安装依赖，不安装当前目录

formats:
  - htmlzip
  - pdf
