name: Render Rmd to Markdown

# 触发条件：push、pull request 或手动触发
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  render-rmd:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 安装 R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'
          install-packages: rmarkdown,knitr

      # 3️⃣ 渲染 Rmd -> Markdown
      - name: Render Rmd to Markdown
        run: |
          Rscript -e "rmarkdown::render('rmd/CHESS.Rmd', 
                                         output_format='md_document', 
                                         output_file='docs/source/CHESS.md')"

      # 4️⃣ 提交生成的 Markdown 回仓库
      - name: Commit generated Markdown
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/source/CHESS.md
          git diff --cached --quiet || git commit -m "Auto-render CHESS.Rmd to Markdown [skip ci]"
          git push
