name: Render Rmd for ReadTheDocs

on:
  push:
    paths:
      - 'rmd/**.Rmd'
  workflow_dispatch:

jobs:
  render-rmd:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - uses: actions/checkout@v3

      # 2. 设置 R 环境（官方 action，稳定）
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'  # 可根据需要调整

      # 3. 安装系统依赖（Pandoc、libcurl、libssl、libxml2）
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc libcurl4-openssl-dev libssl-dev libxml2-dev

      # 4. 安装 R 包依赖
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c(
            "rmarkdown", "knitr", "mvtnorm", "MASS", 
            "Rcpp", "RcppArmadillo", "remotes"), 
            repos="https://cloud.r-project.org")'

      # 5. 安装开发版本的 CHESS（如果需要）
      - name: Install CHESS package
        run: |
          Rscript -e 'remotes::install_github("xxx/CHESS")'

      # 6. 渲染 Rmd -> Markdown，用于 RTD
      - name: Render CHESS.Rmd to Markdown
        run: |
          Rscript -e "rmarkdown::render(
            input='rmd/CHESS.Rmd', 
            output_file='docs/source/CHESS.md', 
            output_format='md_document')"

      # 7. 列出生成文件确认
      - name: List output files
        run: ls -l docs/source/
