name: Render Rmd for ReadTheDocs

# 可以手动触发，也可以在 Rmd 文件改动时触发
on:
  push:
    paths:
      - 'rmd/**.Rmd'
  workflow_dispatch:

jobs:
  render-rmd:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库
      - uses: actions/checkout@v3

      # 安装 R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      # 安装 R 包依赖
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown","knitr","mvtnorm","MASS","Rcpp","RcppArmadillo","remotes"), repos="https://cloud.r-project.org")'

      # 渲染 Rmd -> Markdown
      - name: Render CHESS.Rmd
        run: |
          Rscript -e "rmarkdown::render('rmd/CHESS.Rmd', output_file='docs/source/CHESS.md', output_format='md_document')"

      # 可选：列出生成文件
      - name: List output
        run: ls -l docs/source/
