name: Render Rmd to Markdown

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  render-rmd:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - uses: actions/checkout@v3

      # 2. 安装 R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      # 3. 安装 R 包
      - run: |
          install.packages(c('rmarkdown','knitr'), repos='https://cloud.r-project.org')

      # 4. 渲染 Rmd -> Markdown
      - run: |
          Rscript -e "rmarkdown::render('rmd/CHESS.Rmd', output_format='md_document', output_file='docs/source/CHESS.md')"

      # 5. 提交生成的 Markdown
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/source/CHESS.md
          git diff --cached --quiet || git commit -m "Auto-render CHESS.Rmd to Markdown [skip ci]"
          git push
